#pragma once

//Sourced from GLFW.h.

#define PRISM_MOUSE_BUTTON_1         0
#define PRISM_MOUSE_BUTTON_2         1
#define PRISM_MOUSE_BUTTON_3         2
#define PRISM_MOUSE_BUTTON_4         3
#define PRISM_MOUSE_BUTTON_5         4
#define PRISM_MOUSE_BUTTON_6         5
#define PRISM_MOUSE_BUTTON_7         6
#define PRISM_MOUSE_BUTTON_8         7
#define PRISM_MOUSE_BUTTON_LAST      PRISM_MOUSE_BUTTON_8
#define PRISM_MOUSE_BUTTON_LEFT      PRISM_MOUSE_BUTTON_1
#define PRISM_MOUSE_BUTTON_RIGHT     PRISM_MOUSE_BUTTON_2
#define PRISM_MOUSE_BUTTON_MIDDLE    PRISM_MOUSE_BUTTON_3
